name: Continuous-Integration


on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
  #Execute a workflow manually
  workflow_dispatch:
    inputs:
      browserName:
        description: 'Browser type'
        required: false
        type: string
        default: 'CHROME'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'


      #Dependencies and run test
      - name: Build with maven
        run: |
          cd Test-Sauce-Demo
          mvn clean
      - name: Run tests
        run: |
          cd Test-Sauce-Demo
          mvn -DbrowserName=${{ inputs.browserName || 'CHROME' }} verify

        #Allure Get history
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
        #Generate report
      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ${{ vars.ALLURE_RESULTS_PATH }}
          gh_pages: gh-pages
          allure_report: Test-Sauce-Demo/allure-report
          allure_history: Test-Sauce-Demo/allure-history

        #post report
      - name: Deploy report to Github Pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: Test-Sauce-Demo/allure-history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

















